### ISSUE TITLE
Fix TextParsable UTCTime instance to be backward compatible with older time

### ISSUE THREAD

**Issue by adinapoli** [cdornan/enum-text#1]
cc @cdornan @adamgundry

Given this program:

```hs
{-# LANGUAGE TypeApplications #-}

module TestUTC where

import Data.Time
import Text.Read

main :: IO ()
main = print @(Maybe UTCTime) $ readMaybe "2020-01-01 10:12:30"
```

The parsing of this `UTCTime` differs from time `time-1.8.0.2` and `time-1.9.3`:

```
stack --resolver lts-14.10 --no-system-ghc exec runghc -- TestUTC.hs
Just 2020-01-01 10:12:30 UTC

stack --resolver lts-17.5 --no-system-ghc exec runghc -- TestUTC.hs
Nothing
```

I haven't investigated exactly what change in `time` triggered it (possibly the handling of a `ZonedTime`) but the current `instance TextParsable UTCTime` behaves differently between `time` versions.

As discussed with @adamgundry, possibly the easiest fix would be cribbing the [parseUTC](https://hackage.haskell.org/package/api-tools-0.9.0.0/docs/Data-API-Time.html#v:parseUTC) from `api-tools` and use it here, as it does the right thing. Compare:

```hs
{-# LANGUAGE TypeApplications #-}

module TestUTC where

import Data.Time
import qualified Data.API.Time as API
import qualified Data.Text as T
import Text.Read

main :: IO ()
main = do
  print @(Maybe UTCTime) $ readMaybe "2020-01-01 10:12:30"
  print @(Maybe UTCTime) $ API.parseUTC (T.pack "2020-01-01 10:12:30")
```

It yields:

```
stack --resolver lts-14.10 --no-system-ghc exec --package api-tools-0.9.0.0 runghc -- TestUTC.hs
Just 2020-01-01 10:12:30 UTC
Just 2020-01-01 10:12:30 UTC

stack --resolver lts-17.15 --no-system-ghc exec --package api-tools-0.9.0.0 runghc -- TestUTC.hs
Nothing
Just 2020-01-01 10:12:30 UTC
```

**Comment by adamgundry** [comment]
I think this is this bug in `time`: https://github.com/haskell/time/issues/128

Looks like it is fixed in `time-1.11`.

**Comment by cdornan** [comment]
Indeed. @adinapoli is switching to `time-1.11` an option?

**Comment by adinapoli** [comment]
> Indeed. @adinapoli is switching to `time-1.11` an option?

There are two issues with this:

* `time` is a boot package, so we would need to be on GHC 9.2.x to depend "cleanly" on it;
* If we patch `enum-text` to use this version of `time`, we cannot guarantee that downstream packages that depends on it would override the version of `time` by using `allow-newer` or `allow-older`, which would arbitrarily trigger the bug.

Considering all that, I feel like at least for the time being (until `time-1.11` becomes de facto) having a fix like I've suggested above is the best solution.

**Comment by cdornan** [comment]
Sure 👍
